version: 2

project_name: manapool

# Disable binary builds since this is a library
builds:
  - skip: true

release:
  github:
    owner: repricah
    name: manapool
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
